# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed8831e62278f19cd0728364657e3ad897ebbfc0fd0ef0d923faa10ed4d41befa21273da186c6f8501c7cd4a9ca83dca83fdbf3ac2a282a015e20f214debe6ff

test:
  secret_key_base: c9dbf5c092292e2f6ac5ea2dbe7326cf932a5a643ca49cfe0add58c94ae7e2572eec40deba250cf4c06b153cadcf5614d4977f3489751d8cd30d21a6994f57b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
